### ISSUE TITLE
pfd::notify locks main thread?

### ISSUE THREAD

**Issue by DJLink** [samhocevar/portable-file-dialogs#11]
Hi,
I'm using notifications like this
```
pfd::notify not("Title", "My message", pfd::icon::info);
```

but it seems the main thread gets locked until the OS notification is finished displaying. I'm using Windows 10. I guess I could launch a new thread to call it but is there any way to prevent this?

**Comment by samhocevar** [comment]
Thanks for the report. This could be avoided by directly fixing portable-file-dialogs, so I just did that!

**Comment by DJLink** [comment]
oh wow that was fast, thank you so much :)
