### ISSUE TITLE
Getting this error when compiling on Windows (mingw32 with partial C++11 support)

### ISSUE THREAD

**Issue by wheremyfoodat** [samhocevar/portable-file-dialogs#16]
![image](https://user-images.githubusercontent.com/44909372/63028771-1bbad600-beb8-11e9-9d2d-6193e6a1badf.png)

**Comment by DJLink** [comment]
does your compiler version has support for std::future? I've come across a few posts of other devs with similar error and it was a version that did not had that function implemented.

**Comment by funbiscuit** [comment]
I confirm that I have this error with msvc version 14.0 (both x64 and x86). Mingw64 with latest gcc compiles successfully. Also I don't see any point in this callback. If I comment it out everything works just fine with both mingw and msvc. Maybe it should be deleted? By the way, custom title is not displayed even with callback. I just see standard "Browse folders" title.

**Comment by samhocevar** [comment]
@funbiscuit can you paste your msvc error? The error above is from GCC on a platform that only partly supports C++11 and does not have `std::future`.

**Comment by funbiscuit** [comment]
@samhocevar 

```
C:\projects\portable-file-dialogs\portable-file-dialogs.h(499): error C2065: 'callback': undeclared identifier
C:\projects\portable-file-dialogs\portable-file-dialogs.h(499): error C2100: illegal indirection
```

Commenting out lines 497 to 501 gets rid of it and everything works fine. You did mention in Issue #14 that this is a compiler bug (in VS2015)

**Comment by samhocevar** [comment]
@wheremyfoodat it appears that your current toolchain (mingw32) does not fully support C++11, namely the `std::future` feature.

It [would seem](https://stackoverflow.com/a/14042343/111461) that installing [the POSIX threads API for mingw32](https://osdn.net/projects/mingw/releases/p15696) could solve the issue. Please let me know!

**Comment by samhocevar** [comment]
@wheremyfoodat the [mingw-std-threads project](https://github.com/meganz/mingw-std-threads) now also supports `std::future`, it could be a good solution for you. I have successfully used that project in the past.

**Comment by samhocevar** [comment]
I am closing this issue because `std::future` is too convenient and I do not wish to replace it with something else that would probably be cumbersome to maintain. There are several ways to fix it:
 - use a compiler that fully supports C++11
 - use the [mingw-std-threads project](https://github.com/meganz/mingw-std-threads)
 - install the [POSIX threads API for mingw32](https://osdn.net/projects/mingw/releases/p15696)
