### ISSUE TITLE
Using IFileDialog for folder selection on Windows

### ISSUE THREAD

**Issue by funbiscuit** [samhocevar/portable-file-dialogs#18]
For Windows Vista and higher it is recommended to use `IFileDialog` to select folders (which gives much nicer and usable dialog), but this drops support for Windows XP. I wonder whether this support is needed? Or maybe it should be done with some define to choose appropriate version at compile time.
It should not be hard to write (basic code takes just 30 lines) and I could make a pull request later. But what approach should I use? Just replace existing code for folder select (dropping xp support) or add new one which is activated with some define (what should it be named?)?

That's a basic code. Returns `nullptr` on cancel or utf8 string (supposing you have helper functions `utf8_to_wchar` and `wchar_to_utf8`

```
char* get_folder(const char* title)
{
    IFileDialog *pFileDialog;
    HRESULT hr = CoCreateInstance(CLSID_FileOpenDialog, NULL, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&pFileDialog));

    if (FAILED(hr))
        return nullptr;

    auto wtitle = utf8_to_wchar(title);

    // Set the dialog title and option to select folders
    pFileDialog->SetOptions(FOS_PICKFOLDERS);
    pFileDialog->SetTitle (wtitle);
    hr = pFileDialog->Show (GetForegroundWindow());
    //result of utf8_to_wchar() should be deleted
    delete[](wtitle);

    char* result = nullptr;
    if (SUCCEEDED(hr))
    {
        IShellItem* pItem;
        hr = pFileDialog->GetFolder ( &pItem );

        if (SUCCEEDED(hr))
        {
            wchar_t* wstr;
            std::cout<<pItem->GetDisplayName(SIGDN_FILESYSPATH, &wstr);
            result = wchar_to_utf8(wstr);
            CoTaskMemFree(wstr);
            pItem->Release();
        }
    }
    pFileDialog->Release();
    //result of wchar_to_utf8() should be deleted
    return result;
}
```

As a side note. IFileDialog will not require creating callback function (which creates error with msvc 14.0) because title can be set without any callback. As well as default path.

**Comment by samhocevar** [comment]
I would suggest a runtime solution, involving a `is_vista()` function (alongside `is_osascript()`) which then chooses between the two implementations. Since `GetVersionEx` is deprecated I don’t have a good suggestion on how to implement the check, though, so maybe checking for the `CoCreateInstance` return value and falling back to the old implementation could work, too.

FYI, the `wchar_to_utf8` functions exist for `std::string` as `internal::str2wstr()` and `internal::wstr2str()`.

**Comment by funbiscuit** [comment]
As pointed in this answer https://stackoverflow.com/a/35615667 there is a helper function in windows 8.1 sdk. So it can be written as just `IsWindowsVistaOrGreater()`. Which compiles on both mingw and MSVC15.

**Comment by funbiscuit** [comment]
PR #19 adds support for IFileDialog
