### ISSUE TITLE
Unable to locate SHCreateItemFromParsingName(SHELL32.dll) on Windows XP

### ISSUE THREAD

**Issue by funbiscuit** [samhocevar/portable-file-dialogs#20]
When running new code that supports `IFileDialog` on windows XP it creates following error:
Entry point to `SHCreateItemFromParsingName `was not found in SHELL32.dll
Because windows tries to link all external functions at startup and does not find `SHCreateItemFromParsingName` function in shell32.dll (because there is no one in windows XP).

This seems to be fixed by either adding delay loading for shell32.dll (linker flag  `/DELAYLOAD:"shell32.dll"`) or loading this dll manually with `LoadLibrary` and manually finding function `SHCreateItemFromParsingName`.

@samhocevar what approach do you consider appropriate for your library? Specifying delay loading of dll for visual studio builds or just writing manually loading of this function?

**Comment by samhocevar** [comment]
I would greatly prefer the `LoadLibrary` approach, so that `#include "portable-file-dialogs.h"` remains the only thing the user has to do.

**Comment by funbiscuit** [comment]
Fixed in commit 3e79c8c
