### ISSUE TITLE
windows compiling error

### ISSUE THREAD

**Issue by liwind** [samhocevar/portable-file-dialogs#28]
https://github.com/samhocevar/portable-file-dialogs/blob/ece1202552b887bb2dc72d0364f5b2069639e53c/portable-file-dialogs.h#L542

quotation mark using GB2312 which is Chinese character

suggests  modified it to utf-8 character to avoid this error

**Comment by samhocevar** [comment]
The character _is_ encoded in UTF-8, as 0xE2 0x80 0x9C (for Unicode character U+201C Left Double Quotation Mark).

What Git client do you use? Maybe it has corrupted your file locally. Also, what compiling error do you get?

**Comment by liwind** [comment]
It is perfect in my linux mint with Clion. But in my windows10 (chinese language) with visual studio 2019, it throws Compiler Error C2334: unexpected token(s) preceding ': or {'; skipping apparent function body. 
After checking, the Double Quotation Mark is Chinese character. When i modified it to english character,  it performs well.

**Comment by samhocevar** [comment]
I added a `.` character at the end of this line to see what happens. These two characters also appear on line 408 and 425 so it is weird that you would only get the error for line 542. Please let me know if the problem disappeared!

**Comment by liwind** [comment]
Great,  the problem disappeared! Thanks.
It is a strange format issue with VS2019.
