### ISSUE TITLE
Default filename for save?

### ISSUE THREAD

**Issue by cmaughan** [samhocevar/portable-file-dialogs#29]
Great, useful library :) It has the more modern find folder UI too on windows.
One small omission, as far as I can see: there's no way to pass a default filename to the save dialog.  You can provide a default folder, but not a default name to put in the save box.

**Comment by samhocevar** [comment]
The `default_path` argument is supposed to accept a full file path, too, but I realise the Windows implementation has a bug. Thanks for reporting this!

**Comment by cmaughan** [comment]
Yeah, I should have mentioned that I tried that already (on Windows) ;-)
