### ISSUE TITLE
Default path disregarded

### ISSUE THREAD

**Issue by csp256** [samhocevar/portable-file-dialogs#31]
On Windows, using up-to-date VS 2019, the default path is not respected:

```
auto f = pfd::open_file(
        "Choose files to read", 
	fs_path.string(),
	{ "Files ending with: " + ext, "*" + ext },
	true);
```

Even though `fs_path` is a valid `std::filesystem::path` the file selection window always opens to whichever directory I last selected a file from.  

I've tried relative and absolute paths, with `/` and `\` separators.

**Comment by funbiscuit** [comment]
It is intended behavior of used windows API. There is a comment in source file:
https://docs.microsoft.com/windows/win32/api/shobjidl_core/nf-shobjidl_core-ifiledialog-setfolder
That's why PFD uses SetDefaultFolder instead of SetFolder.

**Comment by samhocevar** [comment]
I have changed the API so that `open_file` uses options instead of opaque booleans, and added the new `force_folder` option.

Comments regarding the API are welcome.

This code should work as you expect:

```
auto f = pfd::open_file(
        "Choose files to read", 
	fs_path.string(),
	{ "Files ending with: " + ext, "*" + ext },
        pfd::opt::multiselect | pfd::opt::force_folder);
```

**Comment by samhocevar** [comment]
I believe this issue is fixed. If it does not suit your needs, feel free to reopen.
