### ISSUE TITLE
The result has extra quotation marks appended to it when more than one file is selected

### ISSUE THREAD

**Issue by 60rntogo** [samhocevar/portable-file-dialogs#39]
Thanks for implementing `kill`. The segfault I mentioned in the other issue is caused by some spurious symbols in the returned file paths. Steps to reproduce:

1. Build examples using the provided makefile. (I built on Ubuntu 20.04 with gcc 9.3.0.)
2. Run example.
3. In the open dialog box select more than one file.
4. In the output observe that every file path is enclosed in extra single quotation marks `'`, except that the first path has no quotation mark at the front and the last one has no quotation mark at the back. (As a result this happens to be OK if there is only one path.)

So it appears that something is messed up with formatting the selected file paths.

**Comment by samhocevar** [comment]
Thanks for the report! I introduced a regression when I replaced `popen()` with `execvp` to implement `kill`. It is fixed in `master`.
