### ISSUE TITLE
bug: Multiselect open and utf8 filename

### ISSUE THREAD

**Issue by herodees** [samhocevar/portable-file-dialogs#48]
Platform: windows
Repr:
There is a bug inside m_async->start lambda. If you try to open multiple files, and first one contains special characters f.e. "test - kópia.png", filename size will be different then wcslen(p), so next filename will loose first character/s.
`
 for (wchar_t const *p = woutput.c_str(); *p; )
{
            auto filename = internal::wstr2str(p);
            p += filename.size();
`
Fix:
`
 for (wchar_t const *p = woutput.c_str(); *p; )
{
            auto filename = internal::wstr2str(p);
            p += wcslen(p);
`

**Comment by samhocevar** [comment]
Well spotted, thanks!
