### ISSUE TITLE
[Solved] Using File Open API on ImGui

### ISSUE THREAD

**Issue by valotam** [samhocevar/portable-file-dialogs#5]
I have seen your reply in an issue of "file system dialogs" from ImGui, [https://github.com/ocornut/imgui/issues/88#issuecomment-431040283](https://github.com/ocornut/imgui/issues/88#issuecomment-431040283).
Your API's features are so nice that I am tring to use your File Open API on ImGui(currently, my project is based on glfw-opengl3-demo.)
But an error that freeze the graphic interface happened and the file open dialog could not appear if I pasted your example codes  
(Example 3: asynchronous file open) [https://github.com/samhocevar/portable-file-dialogs/issues/3#issue-371472393](https://github.com/samhocevar/portable-file-dialogs/issues/3#issue-371472393).

The console were printing messages (as you can see it below), the others were stopped though.
![image](https://user-images.githubusercontent.com/26079796/47854681-aba9fa80-de25-11e8-8e72-47bd07e5e2c5.png)

It is demo codes

```c++
static void ShowExampleMenuFile()
{
    ImGui::MenuItem("(dummy menu)", NULL, false, false);
    if (ImGui::MenuItem("New")) {}
    if (ImGui::MenuItem("Open", "Ctrl+O"))
    {
        // File open dialog
        auto dialog = pfd::open_file("Select file to open");

        // Do something while waiting for user input
        while (!dialog.ready(1000))
        std::cout << "Waited 1 second for user input...\n";

        // Act depending on the user choice
        std::cout << "Number of selected files: " << dialog.result().size() << "\n";
    }
    if (ImGui::BeginMenu("Open Recent"))
    {

```

Would you let me know how the File Open API should be applied to ImGui if you have tried?

Thank you in advance.

**Comment by samhocevar** [comment]
The problem is that your `while` loop waits indefinitely for user action. You need instead to return as soon as possible and check again at each iteration of the main loop.

Here is one way it could work. You need to ensure that the user cannot click on `Open File` if there is already a dialog opened. I do this using the `Disabled` item flag, which requires `#include "imgui_internal.h"` (making these flags available to the user are still in Dear ImGui’s TODO):

	static pfd::open_file *open_file;

	ImGui::PushItemFlag(ImGuiItemFlags_Disabled, open_file != nullptr);
	if (ImGui::Button("Open File"))
		open_file = new pfd::open_file("Choose file", "C:\\");
	if (open_file && open_file->ready())
	{
		auto result = open_file->result();
		if (result.size())
			std::cout << "Opened file " << result[0] << "\n";
		delete open_file;
		open_file = nullptr;
	}
	ImGui::PopItemFlag();

**Comment by valotam** [comment]
Wow it has been solved! Thanks a lot @samhocevar!
