### ISSUE TITLE
Returning empty result from Windows libraries

### ISSUE THREAD

**Issue by paladin-t** [samhocevar/portable-file-dialogs#63]
When select from the virtual library directories on Windows, the directory dialog returns empty result.

![图片](https://user-images.githubusercontent.com/2062224/147181124-7638a0f6-89bd-4463-a96b-25558067e1c9.png)

**Comment by samhocevar** [comment]
Hello! I have been unable to reproduce the problem on Windows 10 and Windows 11. What operating system are you using?

**Comment by samhocevar** [comment]
On second thought, maybe you wanted to return the actual selected library? It could do the following:
 - if the user selects **Pictures/Sample Pictures** you will get something like `"C:\Users\Public\Pictures\Sample Pictures"`
 - if the user selects **Pictures** you will only get `"Pictures"`

But how can you handle the second case in a portable way?

**Comment by paladin-t** [comment]
ty for the update! i’ll check it.
