### ISSUE TITLE
Conan integration

### ISSUE THREAD

**Issue by jovobe** [samhocevar/portable-file-dialogs#7]
Hi,

I just stumbled upon your library and I'm going to use it for my current project. As I am using [conan](https://conan.io/) to manage my dependencies I wanted to ask if you are planning to release a conan package of it in near future.

Best regards
Johan M.

**Comment by samhocevar** [comment]
Sure, I did not know about conan but after having a look I’m definitely considering it.

**Comment by hnOsmium0001** [comment]
https://github.com/conan-io/conan-center-index/pull/4856
This repo has been packaged in center index, and this issue can be closed.

**Comment by samhocevar** [comment]
Thanks for mentioning this. Are you familiar with how this repo works? Should I contact someone when a new release is made?

**Comment by samhocevar** [comment]
Thanks for the explanation. I'll close this issue, then.
