### ISSUE TITLE
Retry treated as pfd::button::cancel in Abort-Retry-Ignore dialog on Mac

### ISSUE THREAD

**Issue by EvanBalster** [samhocevar/portable-file-dialogs#70]
When using `choice::abort_retry_ignore` on Mac, clicking the "retry" button causes `message::result` to yield `button::cancel` instead of the expected value `button::retry`.

As a sidenote, it's a bit odd making "retry" the default option (it's "abort" on Windows, for example).

**Comment by Blatman** [comment]
Agree with this - the portable-file-dialogs are used downstream in the Neutralino project (bug #646) and at the moment I have to modify the portable-file-dialogs.h file on each release. Be great if this is addressed upstream.
This also affects the choice::yes_no: and choice::ok: options.


My mods are -

L1535                           " default button \"Yes\"";
L1536            //              " cancel button \"No\"";

L1547                          " default button \"Retry\"";
L1548            //              " cancel button \"Retry\"";

L1559                          " default button \"OK\"";
L1560            //              " cancel button \"OK\"";

Note: the mappings(256) lines may need altering also

**Comment by samhocevar** [comment]
Thanks for the multiple bug reports! I believe all of them are fixed in 15ecada.
