### ISSUE TITLE
how can i save a txt file?

### ISSUE THREAD

**Issue by kone9** [samhocevar/portable-file-dialogs#71]
how can i save a txt file?

I'm implementing your library to use it with the godot engine and C++, amazingly it works very well, but I can't find a way to take a file and save it somewhere else.
There is no example in this source code, there is only to search.

The idea is Using Windows' native file dialog with godot engine and c++
thank you

![Screenshot_2](https://user-images.githubusercontent.com/12847027/168428970-470af01b-30b7-47ad-8ba3-bffacc668e05.jpg)

![Screenshot_1](https://user-images.githubusercontent.com/12847027/168428887-a047df27-f3f1-446d-9613-a73688268fac.jpg)

https://godotengine.org/qa/108702/using-windows-native-file-dialog

**Comment by kone9** [comment]
I've been testing all day with windows 10 and it seems to me that it has a bug he knows... There is no way I can save a file.

**Comment by X-rays5** [comment]
I think you're supposed to write yourself to the path you get from the result() call. The options force_overwrite seems to just be to suppress the popup dialog. That's what I'm doing atleast.

**Comment by kone9** [comment]
> I think you're supposed to write yourself to the path you get from the result() call. The options force_overwrite seems to just be to suppress the popup dialog. That's what I'm doing atleast.

And how do I write in the path?
For example with TKinter with python there is a method for that.
I feel that the library does NOT solve the usual problems when saving files, I mean take another file and save it, etc.
Likewise, thanks for the suggestion, I didn't even imagine that, I thought it was already solved.

So in Tkinter when you call the asksavefile method, it not only returns the path, it also creates a file that can be overwritten and saved to that location.
I leave an example image with TKINTER
![Screenshot_3](https://user-images.githubusercontent.com/12847027/168450055-1fea4fff-8735-427c-bf11-069e29ec5ae2.jpg)

**Comment by kone9** [comment]
Well in the end I did as I was told above use the return location.

-Save the ".txt" information in a string
- Then I create a new file and save it to the return location that da file knows.

I leave a reference image.
I use the Godot Engine API for strings among other things, so if you want to do something similar you'll have to investigate how to create and save files with the original C++ API.
Thank you very much for creating this amazing tool
![Screenshot_2](https://user-images.githubusercontent.com/12847027/168453958-01e177d7-e15a-4feb-9238-2c5b5670da23.jpg)

**Comment by samhocevar** [comment]
Yes, I’m sorry about that, but actually saving files is far beyond the scope of this library. There are so many ways to read and write data to files that it would quickly become unmanageable.

I see that you found how to do it with Godot, that’s great! The C++ language itself offers plenty of solutions out of the box:
 - https://www.cplusplus.com/doc/tutorial/files/
 - https://en.cppreference.com/w/cpp/filesystem
