### ISSUE TITLE
Error on macOS Mojave 10.14.4

### ISSUE THREAD

**Issue by jovobe** [samhocevar/portable-file-dialogs#8]
Hi,

I just tested your library on macOS Mojave 10.14.4 and get an empty `vector` from:
```

auto selection = pfd::open_file("Select a file").result();
```
even when a file is selected.
After some short debugging I found the internal state in `m_exit_code` of `pfd::internal::executer` to be 256 after selecting a file and querying the result.

**Comment by samhocevar** [comment]
Thanks! I could reproduce the problem and I just fixed it!

**Comment by jovobe** [comment]
> Thanks! I could reproduce the problem and I just fixed it!

You are welcome! Oh no, I saw it too late and just created a PR to fix this 🙈 It's up to you to decide what to do with it.

**Comment by samhocevar** [comment]
I think my fix is enough and I prefer to have most of the logic in C++ rather than AppleScript. Thanks for the patch though; I'm an absolute beginner in AppleScript so it helped me understand it a bit better.
